---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-607a21419266506e2425698a6606ab6d
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/microsauce/gitops-config.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/microsauce/podinfo-deploy.git
